### ISSUE TITLE
error al migrar las tablas

### ISSUE THREAD

**Issue by sald19** [searchsam/cupboard#7]
![image](https://user-images.githubusercontent.com/1674971/65933305-401e3380-e3ce-11e9-9bf1-e7579cea22af.png)

**Comment by searchsam** [comment]
Add `DB_FOREIGN_KEYS=true` on `.env` file or change to `true` the option `foreign_key_constraints` in the sqlite section

 ```php
'sqlite' => [
    // ...
    'foreign_key_constraints' => true,
],
```

on database configuration file `config/database.php`
